### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by benvl** [cmda-be/course-17-18#110]

**Comment by wooorm** [comment]
@benvl Hey! What did you think of the assignment?

**Comment by benvl** [comment]
Vreselijk taaltje, git. Ik heb telkens het gevoel, dat hier een of andere metafoor achter zit die ik niet beheers. Iedere consistentie ontbreekt voor mijn gevoel:

Een “commit” kan je hier blijkbaar ongedaan maken. Dat staat haaks op alle andere gebruiken van “commit” die ik ken in de ICT.

"git reset file.txt" (1.16) is een mix van "remove file.txt" en "reset stage naar eerdere toestand”. Wat  bedoelt git precies met “reset”? 

"git push origin master" (1.11, 1.12) betekent push to origin from master. 
Zoals in "sleep dit naar B van A” - of zie ik het verkeerd.
(geldt ook voor pull)

met "git branch" (1.24) zie je welke branches er zijn, maar je kan er ook een branch mee aanmaken, en er een mee verwijderen, afhankelijk van de parameters. “branch” slaat blijkbaar niet op de handeling (wat ik zou verwachten bij een commando) maar op het lijdend voorwerp. Ik geloof, dat dit mijn unheimliche gevoel verklaart. Ik zou het lijdend voorwerp tussen de parameters plaatsen.

in "git checkout -- file.txt" (1.17) is "file.txt" dat, wat wordt uitgecheckt
in "git checkout clean-up" (1.19) is "clean-up" de actieve branch na checkout (de branch waar men naar toe wordt uitgecheckt)
"git checkout master” moet ik blijkbaar lezen als lezen als "checkout to the master branch” en niet als  "checkout the master branch”? Waar stat “checkout" dan voor? Wat gebeurt er met de inhoud van de branch waarvandaan je uitcheckt?

Ik heb er ook lang over gedaan.

Gelukkig heb ik inmiddels dit gevonden op [wikipedia](https://en.wikipedia.org/wiki/Git). Zodra ik tijd heb kijk ik hier beter naar.

![760px-git_operations svg](https://user-images.githubusercontent.com/3481331/35979354-73107f78-0ce8-11e8-9f61-3b89ffa8c51e.png)

**Comment by wooorm** [comment]
Hey this is essentially the same your email right? I’ll respond to this, instead of there, as you made this later. Awesome notes btw!

Below, I commented on a few of your questions. I think that Git’s man pages are actually pretty good, so if you still have questions, maybe check that (note: for `git reset` you can find the man page with `man git-reset`, etc...)

> Vreselijk taaltje, git. Ik heb telkens het gevoel, dat hier een of andere metafoor achter zit die ik niet beheers. Iedere consistentie ontbreekt voor mijn gevoel:

New things! It has a pretty steep learning curve!

> Een “commit” kan je hier blijkbaar ongedaan maken. Dat staat haaks op alle andere gebruiken van “commit” die ik ken in de ICT.

Well, yes, you can rewrite history. Kind of just like *real* history books, right? 😉

> met "git branch" (1.24) zie je welke branches er zijn, maar je kan er ook een branch mee aanmaken, en er een mee verwijderen, afhankelijk van de parameters. “branch” slaat blijkbaar niet op de handeling (wat ik zou verwachten bij een commando) maar op het lijdend voorwerp. Ik geloof, dat dit mijn unheimliche gevoel verklaart. Ik zou het lijdend voorwerp tussen de parameters plaatsen.

`git branch` does this: “List, create, or delete branches”.
`git checkout` goes to some place in the history (and with `git checkout -b new-branch` creates that place)

P.S. you may like the [Pro Git](https://git-scm.com/book/en/v2) book!
