### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Karinliu** [cmda-be/course-17-18#221]
https://github.com/Karinliu/karinliu-dotfiles

**Comment by wooorm** [comment]
Super awesome @Karinliu! How was your experience working on this?
I love how detailed your readme is, super cool, well done! 👍

You’re doing great, but I thought I’d share some suggestions with you. I’d suggest to first go an relax now before doing anything else though!

1. Your commit messages also include the command you use to commit! Take a look at [your commits](https://github.com/Karinliu/karinliu-dotfiles/commits/master), and note that they contain stuff like `git commit -m "readme file replace"` instead of `readme file replace`. I’m not entirely sure how you’re doing that, but in your terminal, you should be able to just do `git commit -m "readme file replace"` and it should give `readme file replace` as the message?
2. Your `alias backend="cd ./documents/cmd/backend"` only works if you are in your home directory. If you’d use `alias backend="cd ~/documents/cmd/backend"`, I think it should work everywhere!
3. What’s the ` #"` part in your `curl ...` welcome message? Is that a typo?
4. Maybe next to `alias ..="cd .."` you can also do `alias ...="cd ../.."`, and other higher levels?

Anyway, you’re doing awesome, well done!!

**Comment by Karinliu** [comment]
@wooorm I am happy it works! But it took me so long to research everything.
