### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by nguyent047** [cmda-be/course-17-18#222]
https://github.com/nguyent047/nguyent047-dotfiles
This exercise took me way longer than it should have and I don't even know if I did it right.

**Comment by wooorm** [comment]
I’m glad you figured it out @nguyent047! 🎉

They look like a very nice beginning, I’d say that you should update your profile (and repo here on GitHub) if you find new aliases or other useful things!

Also: I think your aliases only work if you’re in your home directory, because they are relative! If you’d use `alias be='cd ~/documents/...` they’d work everywhere!

P.S. Could you share a screenshot of how your terminal looks now when you start it up?

👋

**Comment by nguyent047** [comment]
Thanks for the feedback @wooorm 👌

<img width="492" alt="schermafbeelding 2018-02-10 om 16 16 32" src="https://user-images.githubusercontent.com/32309314/36073014-f7f0f4d2-0f29-11e8-8c77-570c109bb685.png">
