### ISSUE TITLE
Profile assignment dotfiles

### ISSUE THREAD

**Issue by vallleynl** [cmda-be/course-17-18#302]
https://github.com/vallleynl/mydotfiles

Uitleg van installatie gegeven in de README.md

Was wat stoeien met het herladen/clonen van de repo 5 dagen later :)
Maar herhaling helpt het onthouden 👍

Any tips?

**Comment by rijkvanzanten** [comment]
Cool!

The only improvement is that you don't have to wrap these statements in a function, since you immediately invoke it:

https://github.com/vallleynl/mydotfiles/blob/e74c95d4413810aef5fd0adc179294c1e6218567/.bash_profile#L1-L11

Other than that, a small _Pro-Tip™_ for Markdown:

You can enable syntax highlighting _in_ codeblocks! Just add the language you're highlighting after the first three backticks like so:

```
```bash
```

This makes codesnippets a lot more legible  😄

```bash
welcome() {
    #------------------------------------------
    #------WELCOME MESSAGE---------------------

    echo "/// 👋  -  Welcome, Marc  - 👋  ///"
    echo -e ""; cal ;
    echo -ne "Today is "; date #date +"Today is %A %D, and it is now %R"
    echo -e ""
    echo "";
}
welcome;

#Display of emoji / user/ computername/ time
export PS1=' [\e[0;34m\]\u\[\e[m\]@\[\e[0;32m\]\h\[\e[m\] \[\e[0;36m\]\W\[\e[m\] \[\e[0;31m\]\t\[\e[m\]] \e[1;37m[:$(pwd)]\e[m\] 👉 $  '

#Ignrores capitalization wiht tab completion
bind "set completion-ignore-case on"

##=---------Keybinds--------
##=-------------------------
# Go all the way to top of file structure
alias .="open ."
# Go one up in file structure
alias ..="cd .."
# Go all the way to top of file structure
alias ...="cd ~/"

source .z-files/z.sh
```
