### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by civvx** [cmda-be/course-17-18#320]
Here you go! https://github.com/civvx/_dotfiles

**Comment by rijkvanzanten** [comment]
Tip for next time; put the credits in the file / line where you actually got some help or where you used someone else's code. There is no way of knowing who did what in your dotfiles right now 😅

I know you guys worked together on this, but since this actually counts towards your final grade, make sure you don't get flagged for plagiarism in future assignments!

I also mentioned this to @Kjellruiter on his submission: #312

**Comment by civvx** [comment]
You are right! i will be carefull next time putting the credits where i got help. I understand that plagiarism could be a problem but this was just a warming up done together.
