### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by civvx** [cmda-be/course-17-18#379]
https://github.com/civvx/package-

I still have question marks at some steps but working in terminal goes much smoother then before.

**Comment by wooorm** [comment]
Hello,

This is not the assignment. The assignment was to create a project around the given code. The goal was to think about what metadata and documentation a package needs. For example, take this sentence: “Include a `package.json` with a **correct name, version, dependencies, and other metadata**”, or this one: “Add a readme.md as well, **documenting the \[given] code: how to install it, how to use it (with examples), a license**”.

Yes, example projects were given, but the assignment states “**look at them for examples**”. There is no mention of “copy paste them into your project”.

Finally, the assignment reads: **Include a link to your repository, what resources you used, and what part of your project you spend a lot of time on**.

The project you mention is not a project. Rather, it’s a few examples copy pasted together without any correlation or acknowledgement. Instead of using the given resources as examples, as was requested, they were incorporated verbatim and presented as own work. Presenting work as your own is seen, by the Amsterdam University of Applied Sciences (AUAS, or HvA in Dutch), as plagiarism. Additionally, five students handed in the roughly same project at the same time, without mentioning working together.

💁 We don’t like plagiarism and normally report it to our assessment committee (examencommissie in Dutch).  See ¶ 6.1.2 of Teaching and Examination Regulations (TER) for a full definition, but here are a few relevant cases that count as plagiarism:

> a. using or copying someone else’s texts, data or ideas without a full and correct acknowledgement of sources;
> b. presenting the structure or central ideas developed by someone else as your own work or ideas, even when a reference to other authors has been included;
>
> \[…]
>
> e. copying (parts of) media files or other sources, software source codes, models and other diagrams of other people without acknowledgement and allowing it to be held as your own work;
>
> \[…]
>
> g. copying the work of fellow-students and allowing it to be held as your own work;
>
> \[…]

Before I take any action, I’d like to ask you to explain why you acted the way you did in a direct message on Slack to either me or @Razpudding.
