### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by BasPieren** [cmda-be/course-17-18#387]
#### Repo link
Here is the [link](https://github.com/BasPieren/package) to my repo. Links to the used resources can be found in the `README.md` file.

#### Assignment experience
Overall it was a good assignment to follow. 

The steps were described cleary and were good to follow up on. I spend the most time on trying to understand the code that was provided in the `index.js` file. I get the overall idea but don't understand it completely.

**Comment by rijkvanzanten** [comment]
Hey @BasPieren! There are two issues in your `package.json` file which makes the package fail to install...:

```json
{
    "name": "replace-vowels",
    "description": "Replaceses the characters of a word with special characters",
    "version": "1.0.0",
    "license": "MIT",
    "homepage": "https://github.com/BasPieren/package",
    "dependencies": {"repeat-string"}, <<<<<<<<<<<<<<<<<<
    "author": "Titus <tituswormer@gmail.com> (wooorm.com)",
    "contributors": [
        "Titus <tituswormer@gmail.com> (wooorm.com)",
        "Bas Pieren (https://github.com/BasPieren)",
    ],
    "files": [
        "index.js"
    ], <<<<<<<<<<<<<<<<<<
}
```

Make sure to use valid JSON in `package.json` 😄 

_Btw: you can install "`npm`" packages via GitHub too! `npm install BasPieren/package`_

**Comment by wooorm** [comment]
Heyy nice start Bas, but could you fix Rijk’s points above?

* I agree with @rijkvanzanten on the valid JSON for `package.json` (you can run npm install in your project and npm will throw errors if your `package.json` is invalid, which you can then fix)
* Don’t just put the actual code in the readme, use examples to highlight how the code can be used
* Tip: use code blocks instead of inline code spans: [they get highlighted](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
* Tip: use consistent indentation in your `package.json`, this looks messy!

**Comment by rijkvanzanten** [comment]
Unfortunately, you missed [the deadline](https://github.com/cmda-be/course-17-18/blob/master/week-2.md#synopsis-3) of this assignment..
