### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by joostflick** [cmda-be/course-17-18#427]
[Repository](https://github.com/joostflick/package)
I feel like I understand the use of packages a lot better after this assignment.
Had some trouble reading the index.js file at first but I believe I figured it out.

**Comment by rijkvanzanten** [comment]
Awesome! Few little thingies:

- You can shorten the repository field to `joostflick/package` instead of the nested object (works only for GitHub!)
- You can make the `author` field more useful by adding your email address and website like follows: `Rijk van Zanten <rijkvanzanten@me.com> (https://rijks.website)`
- You can omit the `files` and `main` key, since `index.js` and `readme.md` are published by default 🙂
