### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#428]
# Package assignment

## Link to repository
[Repo](https://github.com/FJvdPol/censor-vowel)

## Resources used
* [ccount readme.md](https://github.com/wooorm/ccount#readme)
* [repeat-string package.json](https://github.com/jonschlinkert/repeat-string/blob/master/package.json)

## Recap
This was a fun excercise, mainly to learn on how to explore packages and find out what they do. Writing the README.md was the most fun, since it required me to understand what the package actually does. 
Writing the package.json file was okay, I am still unsure if i left important parts out but if so, I haven't found what.

**Comment by rijkvanzanten** [comment]
Awesome! 

Some extra points to make it _awesomer_:

- Add `.DS_Store` and/or `thumbs.bd` to `.gitignore` to make sure none of those pesky system files get in your repo
- You should leave `package-lock.json` in your repo so your app environment can correctly be reproduced
- I'm not sure what your `test.js` file is.. But if it's a unit testing file (f.e. for Mocha or Jest) you should leave it in the repo, so contributors can test it using the same setup
- The `repeat-string` package is used in the main code and is therefore a `dependency` instead of a `devDependency`
- `readme.md` is always included and can be omitted from files. You can move `index.js` to the `main` key.
- The package name in `package.json` doesn't match the name in the readme installation instructions (`censor-vowel` vs `Vowel`)

**Comment by FJvdPol** [comment]
Thats a good collection of points! Changed the name of the package halfway through writing the readme so apparently I forgot to update the package.json #oops
