### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by matsfeber** [cmda-be/course-17-18#439]
# package
Here is my [repo](https://github.com/matsfeber/package) 

Things i learned with this assignment.

1. How to make a package.json
2. What a [MIT-license](https://github.com/matsfeber/package/blob/master/license.md) is
3. How downloading and using packages work ( i used this with learnyounode but now i understand it better)
4. Some code to censor words

**Comment by rijkvanzanten** [comment]
Hey @matsfeber! Good work.

Few things you can do to improve `package.json`:

- Fix the indentation, everything is on the same line now.
- You can improve the `author` field by adding your email and website: `Rijk van Zanten <rijkvanzanten@me.com> (https://rijks.website)`
- You can shorten the `repository` field by using a string instead of a nested object: `rijkvanzanten/repo`. (works only for github)

🎉
