### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by theonejonahgold** [cmda-be/course-17-18#451]
Heya! I finished the listing assignment in [this repo](https://github.com/theonejonahgold/plain-http). I really liked the assignment, and actually learnt a lot about the http package (among others) and how it works under the hood. I think it pretty important knowledge to have, so I'm glad I learnt it here. 😊

**Comment by wooorm** [comment]
Are you sure it’s done? 🤔

<img width="880" alt="screen shot 2018-02-26 at 10 06 46" src="https://user-images.githubusercontent.com/944406/36661868-db566fb4-1adc-11e8-8ab0-a941c1a17ddf.png">

**Comment by theonejonahgold** [comment]
Maybe I should've included some sort of testing to make sure it works 😅

**Comment by wooorm** [comment]
I think that instead of `if (mt.lookup(url) == 'text/html') { ... } else { ... }` you can just always send the HTML version back. Even if `foo.css` is requested, it’s fine sending a 404.html back?!

**Comment by theonejonahgold** [comment]
Well that does result in unnecessary bandwidth being used

**Comment by wooorm** [comment]
How? 🤔
I think that's how most servers work, but feel free to prove me wrong!

**Comment by theonejonahgold** [comment]
You're right, most servers do use that method. I just think it's a waste of bandwidth if you have thousands of 404 responses with an unnecessary html payload

**Comment by wooorm** [comment]
Why would you send thousands of 404s? I think it’s more important to just respond with a 404, and tell people what’s up, than to not tell them anything?!

**Comment by theonejonahgold** [comment]
You've convinced me, I've never thought of that.. I'll change the code 😄

**Comment by theonejonahgold** [comment]
I've changed the code! 👌

**Comment by wooorm** [comment]
Nice! Some feedback:

* Why the `<!-- TODO: Revise features list-->` in your readme? Are you still working on that?
* In the GitHub repo settings you can turn off projects and wiki’s support, if you‘re not using them (that’s what I do)
* Add `"private": true` to your `package.json`, that makes sure you can’t accidentally publish projects to npm: useful for exercises like this
* You can use `"repository": "theonejonahgold/plain-http"` in `package.json` when linking to GH, it’s shorter that this current object
* `"bugs": "https://github.com/theonejonahgold/plain-http/issues"`, as well
* Drop the `"scripts"` if you’re not using them, and the default test failure isn’t needed either
* `"main": "index.js"` is the default
* Use longer variables: `mt` works maybe for this small projects, but `mimes` or `mimeTypes` is more descriptive
* Why is `allowedMimes` needed if you’re already using `mime-types`?
* use `path.sep` instead of `/`
* Does this show an index / sitemap for a request to `foo` if `foo` is a directory and has an `index.html`? Or does it show the respective `index.html`
* Is `buf.toString()` needed?
* You‘re doing `mt.lookup(req.url)` three times, maybe store the result in a variable instead of calling it thrice?

👍👍👍
