### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#502]
https://github.com/Marijnone/plain-server/tree/master

First exercises where do able but the i could not figure out the last two.

> Respond with 200 OK and an index.html file if it exists (if /assets is requested and /assets/index.html exists, the server should respond with the contents of that file as if /assets/index.html was requested instead)
Respond with 200 OK and a list of files in the directory if no index.html exists (if /images is requested and /images/index.html does not exists, the server should respond with a nice looking list of files in the /images directory)

I would like to know how to do this since i've spent so much time debugging.

**Comment by rijkvanzanten** [comment]
Quick tip to begin with: add some installation and usage instructions to your readme! 🙂

**Comment by rijkvanzanten** [comment]
In order to get the last two done, you first check if the file req.url + index.html exists. If so, you send it just like you send the other html file. If it doesn't exist (fs errors) you read the directory with `fs.readdir` or by using the `node-dir` package you installed. (make sure to put `node_modules` in .gitignore!)
