### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by Denniswegereef** [cmda-be/course-17-18#504]
I really tried this course but just couldn't figure out to get the last 2 bullet points to work how I wanted.. But I learned a lot to play with the flow of how node works as a server and got the basics and tweaked them a bit by my likings.

In the end I spend alot of time without any result and when I saw this express lecture today I'm quite happy that express exists :)

Link to my [repo](https://github.com/Denniswegereef/listing)

**Comment by rijkvanzanten** [comment]
Feedback:
* Nice usage of `npm run start`
* Note: while handy for development, don't use it to run servers in 'production' mode
* If I request a path without an extension (like `/`), your code doesn't add a `Content-Type` header, since the `mime.lookup` doesn't get any extname passed in. This can be fixed by defaulting to `.html` and only doing the lookup if the extname has been set.
* What where you trying to achieve with [these rules](https://github.com/Denniswegereef/listing/blob/master/server.js#L10-L18)? They currently don't do anything

In `package.json`:
* `mime-types` should be a `dependency` instead of a `devDependency`, since it's required for your app to run.
* Normally, `nodemon` would be used for just development purposes, but since you're using it to start the app (`npm run start`), it should be a `dependency` in this case too
* You can shorten the `repository` field by changing it to just your username and repo: `rijkvanzanten/listing`
* You shouldn't gitignore the `package-lock.json` file. NPM uses this file to check the integrity of the requested modules on install

All in all, good job 😄

**Comment by Denniswegereef** [comment]
Thanks for the feedback!

The three rules that you stated is where I ended last night but couldn't figure it out to continue.. they basically do nothing right now :)
