### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by jessiemasonx** [cmda-be/course-17-18#506]
I've been trying to finish this assignment for so long but I wasn't able to. I found this very difficult. Sometimes I didn't understand what they asked me for, until I asked someone.

I was so glad I could use the video and slides of the lecture because I helped me a lot. 

I think I finished the first 3 steps of the assignment. I just don't know how to do the other 2. Believe me I tried.

[Here's what I did](https://github.com/jessiemasonx/Listing)

**Comment by rijkvanzanten** [comment]
Hey @jessiemasonx! 

It's quite a tough assignment! I do believe you tried 😄 

## Feedback

### Code style
* Watch [the indentation](https://github.com/jessiemasonx/Listing/blob/master/index.js#L22-L36). While it doesn't affect performance / functionality of the code, it makes it quite easy (as a human) to get confused by what goes where (same goes for the HTML pages too).
* It helps the overal "beauty" of the code if you choose certain rules for yourself to stick to. For example: I use only single quote `'` for strings and always add a `;` add the end of lines. It doesn't sound like much, but it actually improves the readability a bit 🙂 

### Readme
* Add installation and usage instructions, so people who are not familiar with your code structure now how to get the server up and running

### Functionality
* Kudos for adding some styling 😄 
* If I go to a non-existent page in a folder (like `/images/rijkiewijkie.html`), the styling of the 404 breaks.. This is due to the fact that you use a _relative_ URL in the `<link>` tag, which makes it try to search for the file in `/images`: `/images/error.css`, while the files exists in the root folder `/error.css`. To fix this, you can change the url in the `link` tag to `/error.css` 😄
