### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#508]
[repo](https://github.com/iSirThijs/listing)

I liked the assignments, but couldn't get everything working the way I want. 

for example if you ask for "localhost:8000/images" it uses the css. but if you add a forward slash / to it it doesn't use the css. Tried fixing it, but I couldn't get it to work.

**Comment by rijkvanzanten** [comment]
Hey @iSirThijs 

The CSS on `/images/` doesn't get loaded, because the `link` tag is setup with a _relative_ url `style.css`, so it looks in the current folder for the file. On `/images/`, it'll try to fetch `/images/style.css`, while it should get `/style.css`. You can fix this by adding the `/` in front of the file name in the `link` tag! 😄 

## Feedback

### Repo
* Don't check `node_modules` into git. While it's only two packages now, this will grow exponentially quick when working on projects. Also, these packages all have their own repos and npm pages, so don't need to be in your repo
* Add installation / usage instructions to the readme

### Code
* Be careful with overly-nested `if else if else if statements`, it makes code very hard to read and understand for people who didn't write it (eg. me ^^). Instead, you could merge certain nested ifs:

```js
// before
if (err) {
        if (err.code == 'EISDIR') {
          doSomething()
        }
}

// after
if (err && err.code === 'EISDIR') {
  doSomething()
}
```

or you could use the fact that a function stops doing anything after you `return` a value. This pattern is often used in this case

```js
function onRead(err, file) {
  if (err) return notFound(res); // this will stop the function
 
  return sendPage(file);
}
```

* Watch the indentation, especially when working with deeply nested contexts (like the if-else structure mentioned above). It'll get quite puzzling to figure out what `{` goes with which `}`
* Why do you have the `index.html` as a separate file, but do you send the `404` html through an inline string? 🤔 
* Try to use _absolute_ URLs instead of _relative_ ones when working with nested paths. For example, your CSS will not load if I try to go to `/path/to/404.html`.

### Functionality
* Good job on getting it to display the filenames!
* Did you forget the `about` page?


All in all, good job 🎉
