### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#510]
# Listing assignment

[Here is my link](https://github.com/timruiterkamp/http-server
)

Overall it was a good challenge, i was trying to make the files in the images directory into a link so that you could click on it but unfortunately i didn't get that part done in time. The /images and /images/ does show the files in the certain directory 😄

**Comment by rijkvanzanten** [comment]
Hey @timruiterkamp! 

Good job 😄 

## Feedback

### Repo
* Add installation / usage instructions to the readme, so people who are not familiar with your file structure (eg. me) know how to get it up and running
* You built the whole project in one commit! Kinda beats the purpose of using version control in the first place 😉 

### Code
* Update the package.json to match your project:
  * Add the author
  * Add the repo
  * Add some keywords
  * Set it to use the right license
* `license.txt` doesn't need the file extension (and is oftentimes uppercased in GitHub) (not right or wrong, but an industry standard)
* The list of if-else statements works for this assignment, but wouldn't be very scalable in real life. If you wanted to add one more image, you would need to update the script to reflect that too. You could try to think of a way to try reading the files based on just the url path, so it would work with every file you put in that folder.
* There's a typo on line 60: `res.statusCOde = 200;`

### Functionality
* The `Content-Type` of ` .jpg` is actually `image/jpeg` instead of `image/jpg`. Due to this wrong header, the browser will download the file, since it doesn't know how to display it 🙂 
* > i was trying to make the files in the images directory into a link so that you could click on it but unfortunately i didn't get that part done in time

  I think you were closer than you might think! You know what the file path should be (`/images` + filename) and you have access to the filename in your loop. I think you should be there by changing [line 31](https://github.com/timruiterkamp/http-server/blob/master/index.js#L31) from

  ```js
  res.write("<li>" + files[i]+ "</li>");
  ```
  to 
  ```js
  res.write('<a href="/images/' + files[i] + '">' + files[i] + '</a>');
 ```
