### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by vallleynl** [cmda-be/course-17-18#511]
Learned a lot about node.js, but have been struggling massively with the last part of the assignment.

- Couldn't find a way to display the list/index of the files in dr's

- Did I get close using the learnyounode 5 answer?

- Good exercise though!

- Sorry i could't complete it :( 

- [linky link to repo](https://github.com/vallleynl/simpleserver)

**Comment by rijkvanzanten** [comment]
Hey @vallleynl!

Good idea to take a look at learnyounode! Unfortunately, that solution is based on using the `pathName` found in the command line interface arguments `process.argv`, which are always undefined in the server, since we start it once with `node index.js` instead of running it with arguments like `node index.js filename.jpg`.

## Feedback

### Repo
* Add a .gitignore file with node_modules in it. You don't want to check all external dependencies (that already have their own repos) into yours!
* Write your own readme! I get that the easiest way to start the assignment is to copy the `plain-server` example and go from there, but theoretically, that's plagiarism 😱
* Add installation / usage instructions for your app to the readme

### Code
* Add some keywords to `package.json` 
* Make sure the links all match your repo instead of the `plain-server` example!
* As mentioned above, the learnyounode solution based on cli arguments isn't going to work for your webserver. However, if you would refactor line 41 to use `route` instead of `pathName`, your solution could work.
* Try to refrain from [using synchronous functions](https://github.com/vallleynl/simpleserver/blob/master/index.js#L15) when working with Node / servers in general.

### Functionality
* The server crashes when loading a page..:
  ```
  /Users/rijkvanzanten/Development/cmda/simpleserver/index.js:40
        if (err.code === 'EISDIR') {
               ^

  TypeError: Cannot read property 'code' of null
    at onread (/Users/rijkvanzanten/Development/cmda/simpleserver/index.js:40:16)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)
  ```

  You can fix this by checking if `err` exists before trying to read `err.code` by changing the `if` statement to `if (err && err.code === 'EISDIR')`
