### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by MonikaaS** [cmda-be/course-17-18#517]
Sorry ! I couldn't make all the steps work 😥

Learned a lot from this assignment. I tried to have fun with it, but sometimes it was very difficult to understand what was asked. Will try to keep working on this assignment, because I want to understand why some steps don't work. 

here is [a link to my repo](https://github.com/MonikaaS/plain-server)

**Comment by rijkvanzanten** [comment]
Heya!

> Sorry ! I couldn't make all the steps work 😥

That's okay! Most people had some troubles with the last two bullets of the assignments. It was a very tough assignment, so no hard feelings there.

## Feedback

### Repo
* Add a `.gitignore` file with `node_modules` in it

### Code
* If you're using the "shorthand" version of an `if` statement (without the curly brackets), I would personally put it on one line, or just add the curly brackets.
  ```js
  // before
  if (req.url == '/')
    req.url += 'index.html'

  // after
  if (req.url === '/') req.url += 'index.html'

  // or
  if (req.url === '/') {
    req.url += 'index.html'
  }
  ``` 
  That way, there is no confusion possible over what functionality goes with what if statement
* It's best practice to always check values strictly (`===`) vs (`==`), just to make sure you don't run into weird hard-to-debug bugs: https://stackoverflow.com/a/359509/4859211

### Functionality
* Does as advertised!
* A little hint to get you started on the directory listing:
  If `fs.readFile` fails, the `err` object contains information on what went wrong (try console.logging `err`). If `err` says it failed because the requested file is in fact a folder, you can run a different `if` statement block:
  ```js
  if (err) {
   if (err.code === 'EISDIR') { ... }
   else { ... }
  }
  ```
  If the requested path is in fact a directory, you can use `fs.readdir` to retrieve the filenames 🙂 

  Hopefully this gives you a good pointer :)
