### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by bengtbennink** [cmda-be/course-17-18#520]
https://github.com/bengtbennink/http-server

Worked on it for a long time but wasn't able to get everything working. I've deleted the code that doesn't work.

**Comment by rijkvanzanten** [comment]
Heya!

> I've deleted the code that doesn't work.
Too bad you didn't use git during the development of your assignment. There is no way of viewing the history of the file now 🙁 

You have the same repo name, and more interestingly the same exact same readFile code as @timruiterkamp.

https://github.com/bengtbennink/http-server/blob/master/server.js#L38-L51
https://github.com/timruiterkamp/http-server/blob/master/index.js#L51-L64

Since it's very unlikely that you write that piece of code using the same typo _and_ the inconsistency in using `"` vs `'` AND seeing the fact that in that point, your code switches from indentation with 4 spaces to 2 spaces, I'm pretty sure you copied it over. Ref @wooorm 

Did you build the rest of the assignment yourself? Please make sure to credit sources when you use them. This is basically plagiarism.

## Feedback

### Repo
* Add installation and usage instructions to your readme
* What's up with the `http-server` submodule?
* Add a `.gitignore` file with `node_modules`, so they don't get checked into git

### Code
* Watch indentation and spacing. It doesn't sound like a big deal, but making sure every `}` matches `{` and all the functions are indented properly makes the code way easier to read.
* You console.log the request.url for every request on line 36. No need to log it again in the if block too (lines 23 & 29)
* There is a typo on line 47 https://github.com/bengtbennink/http-server/blob/master/server.js#L47

### Functionality
* Works as advertised
* Try adding some CSS
