### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by SadisticSun** [cmda-be/course-17-18#521]
Exercise was great to bring back some of the basics I missed, but thank the developer gods for Express. Doing this manually all the time will be a living nightmare. 

Also, note to self: STOP FORGETTING TO UPDATE GITIGNORE. 

Link to repo: https://github.com/SadisticSun/listing-assignment

**Comment by rijkvanzanten** [comment]
Solid! But to be fair, I would've been surprised if it wasn't 😉 

## Feedback

### Repo
* 👍 
* Stop forgetting to add .DS_Store to gitignore 😝 
* Some fields in package.json can get a little more love:
  * repository can be shortened to `name/repo`
  * author is empty
  * keywords is empty
  * license has the wrong license mentioned
* The installation instructions aren't complete. Just installing the npm dependencies doesn't run the app
* 

### Code
* Declaring functions by using `name = () => {...}` actually makes them a `var` in the global scope. You might want to consider prepending the statement with `const` to make sure the function isn't overwriteable: `const getContentType = (query) => {...}`
* The mimetype of a `.jpg` is actually `image/jpeg`, not `image/jpg`. 

_The following is purely preference based. Ignore these if these were by design, if not, I might give you some new insights 🙂 :_
* `getContentType = (query) => query == '/img' ? 'image/jpg' : mimetype.lookup(query)`
  When only dealing with 1 parameter, the `()` are optional
* `query == '/img'` The path in an URL can only be a string. Just to make sure, you're probably better of strictly checking the type too to prevent some weird future bugs `===` vs `==`
* You should consider the maintainability of code when combining variable declarations with arrow functions _and_ ternary operators. Don't get me wrong, it looks very concise and makes you look very smart, but in an open source project this would probably hinder maintainability, seeing not everyone gets what you're doing.

  IMO writing it "the long way" is actually easier to understand
  ```js
  // before
  getContentType = query => query === '/img' ? 'image/jpeg' : mimetype.lookup(query);

  // after
  function getContentType(query) {
    if (query === '/img') {
      return 'image/jpeg';
    }

    return mimetype.lookup(query);
  }
  ```
* The code doesn't pass your own linting command 

### Functionality
* The app doesn't start when running `npm start` (Your start command runs `xo`, which errors out because of styleerrors in your code)
* The `.jpg` mimetype bug makes my browser download the file instead of displaying it in the browser. (And yes, that's a bug, not a feature 😛 
* The `/images/` endpoint times out.. This is most likely because you don't call `res.end()` after you're done writing to the body on line 29

**Comment by SadisticSun** [comment]
Great feedback! 
Regarding the shorthand code, I agree: using it sparingly is advisable when working on a project that is supposed to be maintainable. Most of the time I actually write the 'readable' version, and then convert to the shorthand.

Thanks!
