### ISSUE TITLE
Listing assignment 

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#523]
### Some FB
In the beginnen i thought im gonna make it to the end in a few hours, 
but after some time it was getting a little bit hard. 
So I still have work to do, and learn further to finish this assignment. 
After all it was fun to do till where i went! 

[Here](https://github.com/labraksam/listing) is the link to my repository.

**Comment by rijkvanzanten** [comment]
Heya! Good job 😄 

## Feedback

### Repo
* Add a proper readme (installation / usage instructions etc)

### Code
* Watch your indentation. It's hard to read what is part of what from line 29 onwards. Did the indentation get messed up because you copied this part in? If so, please make sure to list the sources
* AFAICT you don't use the part between 5 and 16

### Functionality
* Works as advertised 👍
