### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#526]
# Listing assignment

## Repository
[link to repository](https://github.com/FJvdPol/simple-server)

## Feedback
I really enjoyed this assignment because it was a really challenging one. Working with HTTP is totally new to me so it was tough to make the code working. 
Especially the part where you have to check wether a repository has an index.html file or not was difficult for me. What to do if the repository did contain files, but didn't contain an index.html?
I think the code I've written in the end could be much more simple, but I'll have to work with these kind of assignments alot more to get to that point.

**Comment by rijkvanzanten** [comment]
Heya! Awesome work 😄 

## Feedback

### Repo
* Very nice readme! You're one of the few people that actually wrote a useful readme
* Solid package.json too 👍 
* `license.md` is often called `LICENSE`. Not a problem, more of an industry standard
* The examples listed are wrong: ~localhost/8000/...~ localhost:8000

### Code
* Try not to use synchronous (demanding) functions (like `fs.existsSync`) in Node / server code. Synchronous code blocks the application. For example, while the application is checking if the file exists, all other code is being blocked until its done. So if someone else was trying to look at the site at the same time, the server wouldn't respond since it's busy with the synchronous code. More info: https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/
* The `mimetype` for a `.jpg` is the same as for a `.jpeg`: `image/jpeg`. Keep in mind that mimetypes aren't just simply a word followed by the extension. For example, the mimetype for `.svg` is `image/svg+xml`.
* Watch the indentation. The function on line 54 has some weird indentation going on which threw me off a bit
* `throw`ing something in JavaScript is actually a thing. Your `throwFourOFour` function doesn't `throw` anything, so you might want to consider calling it `sendFourOFour` or something 🙂 
* While it works fine for this assignment I don't think you could assume `route.indexOf('.') === -1` means the user is requesting a folder in real life. I think the user will more often than not omit the extension when typing a URL

### Functionality
* Smart trick of making `about` a folder too, so it would work with `/about`
* Does what it's supposed to do 👍
