### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by Sam-Guliker** [cmda-be/course-17-18#528]
:fire: https://github.com/Sam-Guliker/Listing :fire:

**Comment by rijkvanzanten** [comment]
Hey @Sam-Guliker! By changing the functions from the "traditional" function syntax to arrow functions, you actually broke your app!

https://github.com/Sam-Guliker/Listing/blob/master/index.js#L27-L30

```js
onchange = (req, res) => {}
```

is like saying `var onchange = function() {}`. Because variables don't get [hoisted](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting) (unlike functions), your reference to `onread` is undefined at the moment it's being used, which results in the following error:

```
ReferenceError: onread is not defined
    at Server.onrequest (/Users/rijkvanzanten/Development/cmda/Listing/index.js:27:43)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```

Protip: Don't use ES6+ just to make the code look cool. If anything, it makes the code less readable, since it uses a less-commonly known syntax. (And in this case, it even breaks the code!)

**Comment by Sam-Guliker** [comment]
Ah thanks for the tip!
Uhm, but when you change the url the code still works?

**Comment by rijkvanzanten** [comment]
## Feedback

### Repo
* The _Usage_ section is meant to show how to use your project, not necessarily how it works. Although, that is a nice addition 🙂 
* I wouldn't call used dependencies `Features`, seeing they're not really features of your application

### Code
* Try to be consistent in the usage of arrow functions vs "traditional" functions. There is no right or wrong in this, but it helps code clarity to choose one and stick with it

### Functionality
* It seems to be missing a big piece of the assignment by only serving the `index.html` and `about.html` pages.. Too bad!
