### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#533]
[Shelter Maikel](https://github.com/Maikxx/shelter)

I liked this exercise, although I think it was a bit much for one exercise. I can imagine a lot of people not going to be able to finish this in time, or maybe I went too hardcore on the validation of the form, not sure. 

Anyhow, a good exercise to learn multer, bodyParser and express, I also used moment for validating the date via the form.

**Comment by wooorm** [comment]
Well done!

* [nice img!](https://github.com/Maikxx/shelter/blob/cb70df96275295b303cfe3583a1601cd123337b0/db/image/89964.jpg)
* seems like a lot of work to refactor all the code 😬 but maybe it helps you understand what’s going on!
* tip: use a different script for nodemon, e.g., `npm run watch` or `live` maybe?
* Doesn‘t `[ i]` in CSS work in your browser? 🤔
* file-filter: as `mimetype === 'image/jpeg'` is either true or false, you could shorten the function to `callback(null, mimetype == 'image/jpeg')`
* try and keep the code in `try` from `try..catch` as small as possible, now there could be many errors going on [here](https://github.com/Maikxx/shelter/blob/cb70df96275295b303cfe3583a1601cd123337b0/server/index.js#L58), instead of just the `db.has` part!
* If the `id` is invalid, [`db.removed`](https://github.com/cmda-be/shelter/compare/cmda-be:5759307...Maikxx:cb70df9#diff-0861d6d6b50d7d695344bf2d86d6e5e6R73) will also throw an error, this time uncaught, meaning it will crash the server
* maybe use [content-type](https://github.com/jshttp/content-type) or [type-is](https://github.com/jshttp/type-is) to check the content type of a request?
* The `(!name.length > 0 || undefined)` part looks weird! To check that `name` has no a `length`, use `name.length < 1` or `name.length === 0` or even `!name.length`. Then, to check that name is undefined, use `name === undefined`! In fact, you could use `name && name.length && type && type.length` for this whole block.
* For the whole POST handling, you could replace most of it with `try { db.add(req.body) } catch (err) { /* 422*/; return; } /* 201 */`. The database already does [all the validation stuff](https://github.com/cmda-be/shelter/tree/master/db#throws-5). Note that some stuff like checkboxes and radio’s need a change in data, but still! ([for example, like this](https://github.com/theonejonahgold/shelter/blob/6632e84cd8807a129d4ac8475694d833e5e40e66/server/index.js#L81))
* You could use `Object.assign` instead of a loop to “patch” data!
* Is it needed to export the app?
* I’m sure you finished these [todo’s](https://github.com/Maikxx/shelter/blob/cb70df96275295b303cfe3583a1601cd123337b0/server/index.js#L348)?
* Nice `handleHttpError` and `renderHtml` functions!
* Are the spans in the labels needed?
* you don’t need id’s on inputs and for’s on labels if you place inputs in labels!
* where are the h3’s coming from? I’m missing h2 and h1!
* I didn’t know about step=any! cool, I used step=0.1 myself
* I’m missing a main.container, so the form is very wide
* Maybe vaccinated Yes/No is more readable than true/false for normal people ;) Or, you could use checkboxes instead of two radio’s for booleans like this!
* is coat required for rabbits? 🤔
* I can’t specify Staten Island Animal Care Center!
* Length can be medium as well!
* It works, super awesome! 💪
