### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by Murderlon** [cmda-be/course-17-18#537]
Neat assignment to refresh my `express` knowledge, also the hand-made database is really cool.
All the [bullet points](https://github.com/cmda-be/course-17-18/blob/master/week-4.md#description) except the extras are in there.

**TIL:**
- [fall-through](https://github.com/Murderlon/shelter/blob/master/server/routes/upload.js#L14-L15) in `switch` statements.
- `res.format()`

https://github.com/cmda-be/shelter/compare/master...Murderlon:master

**Comment by Murderlon** [comment]
Now that I think of it I forgot to properly handle some error's.
Ideally, there should be a catch all route which conditionally renders the error template based on status code and description.

**Comment by rijkvanzanten** [comment]
9 changed files with 8,290 additions and 55 deletions in only 1 commit? 😨 

* +1 on adding the `;`. Team `;` all the way 👊 
* Smart move to use routes
* You have a spelling mistake in the server-started console log: `'listening on http:localhost:1902'`
* No CSS 😢 `Did not parse stylesheet at 'http://localhost:1902/index.css' because non CSS MIME types are not allowed in strict mode.`
* TIL object spread works in Node 🤯
* Why the double spread `const data = { ...{ data: db.all() }, ...helpers };`? Isn't `const data = { ...helpers, data: db.all() };` enough?
* Redirecting on a 404 isn't very user friendly IMO
* [More of the double spreads](https://github.com/cmda-be/shelter/compare/master...Murderlon:master?diff=split&name=master#diff-35ce97214bdb2125ffab07048ca2dba3R24)
* I can't add a decimal value into the weight field f.e. 1.1 throws an error
* Creating a new animal returns `Unprocessable Entity`

<img width="1033" alt="screen shot 2018-03-12 at 9 47 03 pm" src="https://user-images.githubusercontent.com/9141017/37318113-f31ce430-263e-11e8-9875-b1509857681b.png">

**Comment by Murderlon** [comment]
> No CSS 😢 Did not parse stylesheet at 'http://localhost:1902/index.css' because non CSS MIME types are not allowed in strict mode.

That's weird! It worked for me on Firefox, didn't check elsewhere.

> Creating a new animal returns Unprocessable Entity

Same here 🤔
