### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#539]
# Shelter assignment 

[Here is my repo](https://github.com/timruiterkamp/shelter)

## Opinion
Overall it was quite a hard challenge to match the correct code with the questions that had to be answered, it took some time but it was all worth it. Learned a lot about express and communicating with the database! 

## Where I got stuck
Everything works except the image uploading, i tried it with multer but i never got the req.file. So that is the only thing that's not ready yet in the repo.

**Comment by rijkvanzanten** [comment]
Hey @timruiterkamp! Good job :)

* Submitting the form results in a 422 Unprocessable Entity error
* `body-parser` is required to run the app and should be listed under `dependencies` instead of `devDependencies`
* You installed `array-find`, but don't use it anywhere
* CSS / JS isn't working. `http://localhost:1902/index.css` gives a 400 bad request. Most likely because of your check to the DB if the path is valid
* Code looks pretty clean in general. Some small consistency "bugs" here and there, but nothing major. `'` vs `"`, sometimes white rules, sometimes not
* There's a lot going on in the terminal. A lot of warnings, luckily nothing that makes the server crash. You might want to consider to go easy on the console.logs or implement a debugger like [`debug`](http://npmjs.com/debug)
* Good job on the 400 / 404
