### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by SadisticSun** [cmda-be/course-17-18#542]
### How did it go?
I must admit, I thought it would have taken me less time than it has. I had some prior experience with using Node and Express, but it seemed a little rusty. An excellent exercise! Also, I loved the cat pictures <3. Had some issues with handling the status codes as I had never really written handlers for them manually. My lovely colleague and classmate Jonah helped me with some parts, so a big thanks to him.

Small point of feedback for the author: some images were missing ..?

### What would I have done differently?
I probably would have refactored the entire codebase to ES6 and a more OOP style with, for example, classes as an exercise for myself. Secondly, I would have liked to split up functionality (division of responsibilities) in a more MVC (Model - View - Controller) style structure.

### Link
Linky to fork: https://github.com/SadisticSun/shelter

**Comment by rijkvanzanten** [comment]
> Small point of feedback for the author: some images were missing ..?

Good catch! Good extra practice to handle the 404 images in a nice way too ( ͡°  ͜ʖ ͡°) 

## Feedback
* CSS is not working
* It says "No errors" on the error page
* Nice accessible form. Smart move on adding the file mimetype in the input
* I get a 422 error when trying to add a new animal with all the fields filled out. 
* You can safely remove the `if` statement on line 72. Since you `return` in the function when the animal hasn't been found, the `let` can only be `true` at that point in your code.
* It would increase the usability of the server greatly if you would use the `err` you catch on line 117 somewhere. There is no way of knowing what went wrong when posting a new animal right now
* The POST and PUT routes exist, but there is no way of using them from the app. The `/add` endpoint exist, but I can't find a link to it, so I didn't know it was in there.
* Sending a PUT request to `http://localhost:1902/88623` returns 
  ```json
  {
    "errors": [
        {
            "id": 400,
            "title": "Bad Request",
            "detail": "No errors"
        }
      ]
  }
  ```
  Not sure what I put in there wrong..
* Overal: good job on the code. Looks very neat, lintfree,
good consistency, good usage of comments! 💯
