### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by JimvandeVen** [cmda-be/course-17-18#543]
https://github.com/JimvandeVen/shelter 

Worked for at least 10(!) hours on this assignment. I did like it though. Had some troubble understanding how the parser worked. I didn't know the right syntax, ```console.log(addAnimal)``` saved my life. It took me a long time to find out how the parser knows what to take, and from where, within the form.  If it was't so late I'd have tried the extra bulletpoints.

**Comment by rijkvanzanten** [comment]
Hey @JimvandeVen! When trying to run the application with `npm start` I'm immediately greeted by a big `Error: connect ECONNREFUSED 127.0.0.1:3306` error. Seemingly, you're trying to connect to a local MySQL server. Could you add some installation / usage instructions to your readme? I'm not sure how I should setup my database in a way your server expects it...

I'm looking forward to playing around with your server!

**Comment by wooorm** [comment]
@rijkvanzanten That’s because @JimvandeVen started working on Storage already 😉

* [Return after sending a response back](https://github.com/JimvandeVen/shelter/blob/000875e240071b096bdaa9f166a6c3dfca7cf442/server/index.js#L67)! Currently, after a 400, the code still runs to `db.removed(id)`, which throws an error, as you can see in your terminal
* Instead of creating a new `result` for errors (like 400, 404, or 410), you can add an error to the result object you already have!
* If I try to delete an animal with Curl, I get an error, where it actually should be a successful response:
  ```sh
  curl http://localhost:1902/89590 -X DELETE
  {"errors":[{"id":204,"title":"No Content","description":"No Content","detail":"detail"}]}
  ```
  ...204 is successful, not an error!
* Tip: place inputs in a label, that way you don‘t have to use `for` and `id` to link them together!
* You’re not using `id` on inputs, so now they aren‘t linked at all!
* The link to the form doesn’t look very nice!
* You’re using an asterisk for required inputs (like vaccinated), but not for others (like primary color)
* You can use a number input for weight, and to allow decimals, set `step` to `all` or `0.1`!
* Don’t hard link [to the domain and port](https://github.com/JimvandeVen/shelter/blob/000875e240071b096bdaa9f166a6c3dfca7cf442/view/list.ejs#L9), use `/upload.html` in the href and you’re fine!

I’m missing docs! Docs are important!

**Comment by wooorm** [comment]
Oh and your Git and GitHub aren‘t linked together properly, see the GitHub prereq again on how to link them correctly: https://github.com/cmda-be/course-17-18/blob/master/week-1.md#github

**Comment by wooorm** [comment]
Oh and for the “added” part, you can just redirect JSON users as well:

```js
        var newAnimal = db.add(addAnimal)
        res.format({
            json: () => res.json(result),
            html: () => res.redirect('/' + newAnimal.id)
        })
        console.log('added')
```

...can be:

```js
        var newAnimal = db.add(addAnimal)
        res.redirect('/' + newAnimal.id)
```
