### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#544]
# Shelter assignment
[link to repository](https://github.com/FJvdPol/shelter)

## Thoughts
I really enjoyed this assignment, because it was a real challenge. I had never seen express before so I had to look up A LOT of methods in the documentation.
Multer was also a challenge, I added the support for uploading images in a really late stage of the assignment so it was really difficult to really get into it. 
Eventually it all worked out.
The only things I didn't get around to was adding support for PUT and PATCH requests.
Really cool assignment, gave me a good insight in what express can do.

**Comment by rijkvanzanten** [comment]
Hey @FJvdPol! Good job 😄 

Feedback:
* Nicely separated commits
* Updated package.json looks good
* You're one of the few that updated the readme. Appreciated!
* Ternary operators can be quite hard to read, I would recommend you to try to avoid this:
  ```js
  data.vaccinated === 'true' ?
    data.vaccinated = true
    : data.vaccinated = false
  ```
  Instead, you could refactor it to (keeping a ternary):
  ```js
  data.vaccinated = data.vaccinated === 'true' ? true : false;
  ```
  OR (preferably), extract the to-boolean code in to a function, seeing you use it multiple times:
  ```js
  function toBoolean(value) {
    if (value === 'true') return true;
    return false;
  }

  data.vaccinated = toBoolean(data.vaccinated);
  ```
  That way, you can also safely extent the function to work with other values than just the string `'true'`.

  OR you could go "The Node Way"™ and install a dependency that handles this conversion, so you don't have to think about it. The [`boolean`](https://www.npmjs.com/package/boolean) package seems to do exactly what you need:

  ```js
  var toBoolean = require('boolean');
  data.vaccinated = toBoolean(data.vaccinated);
  ```
* You kinda threw me off by setting most of the form options to a default. Oftentimes, it's good practice to give the user good defaults, but in this case there is no good default, since most fields can be anything. 
* You could add some sort of visual cue that a field is required (f.e. an `*` next to the label / legend). I don't know what fields are required or not.
* This is one of the few shelter projects I've seen where I'm not greeted by a 422 cat on upload. Good job! 😄 
* When I posted a new animal, it showed on the top of the list on the homepage. When I refreshed, it was at the bottom?
* Deleting an item works! Even shows a 410 instead of a 404. Awesome 🎉 
* Thanks for adding the comments stating where inspired-by code starts and stops
* I noticed you updated the `index.css` file, but for me, it's not loading the CSS :(
* In cases like these:
  ```html
  <input type="radio" name="data[vaccinated]" id="vaccinated-true" value="true" required>
  <label for="vaccinated-true">It's vaccinated</label>
  ```
  You could choose to put the input _inside_ the label to clean up the code a little bit. There is no right or wrong way, just personal preference really.
  ```html
  <label><input type="radio" ...>Vaccinated</label>
  ```
