### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by MonikaaS** [cmda-be/course-17-18#546]
I think this is a good assignment, I learned a lot from it. Sometimes I found the assignments a bit vague. But I think that is mostly because I'm a beginner at this and I have to look up a lot.

I put a lot of time in it, I think around 11 hours or so. I was very confident at the beginning that I could finish it all, but at the last step I got stuck.. :expressionless:

But I want to keep working at it, because I was so close at finishing the assignment lol.

[my shelter](https://github.com/MonikaaS/shelter)

**Comment by wooorm** [comment]
Thanks for the great detailed readme @MonikaaS! Awesome work, and super well done!! 💪

* Who is `jason`? 🤔
* You [installed `slug`](https://github.com/MonikaaS/shelter/blob/d908e068b17e80a97f4e738b291aed7351dad250/package.json#L21) and [include it](https://github.com/MonikaaS/shelter/blob/d908e068b17e80a97f4e738b291aed7351dad250/server/index.js#L7) but don’t use it anywhere!
* for all the templates, such as `var listPage = ('./list.ejs')`, a) why are the parens around those strings? b) why place them in variables instead of using them in the right place directly? c) the `./` part isn’t needed!
* Why `ListAnimals` instead of `all`, `AnimalDetail` instead of `get`?
* Your [`removeAnimal`](https://github.com/MonikaaS/shelter/blob/d908e068b17e80a97f4e738b291aed7351dad250/server/index.js#L79) doesn’t work! It never removes animals! I’m thinking you mean `db.remove` instead of `db.removed`?!
* In your form handling is [`add`](https://github.com/MonikaaS/shelter/blob/d908e068b17e80a97f4e738b291aed7351dad250/server/index.js#L130) ever truthy? Does the `console.log` ever happen?
* In your [`addAnimal`](https://github.com/MonikaaS/shelter/blob/d908e068b17e80a97f4e738b291aed7351dad250/server/index.js#L126) function, maybe add a `console.log` in the [`catch` to see what `error` it is](https://github.com/MonikaaS/shelter/blob/d908e068b17e80a97f4e738b291aed7351dad250/server/index.js#L125)? Also see the assignment:
  > You should clean the data sent to the server before passing it to db.add, as there are many cases where adding an animal can fail: such as when required fields are missing or if fields have a wrong data type (age and weight should be numbers, vaccinated and declawed a boolean, declawed must be undefined for dogs and rabbits, or when values are empty strings instead of undefined).

Good luck! 💪
