### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by deannabosschert** [cmda-be/course-17-18#552]
This whole assignment in one phrase: **'I tried'**.

Lots of things are probably still not working, such as adding animals via the form; kind of really lost it there.
Tried to do all of the bulletpoints but it just isn't working and I don't know where to check or where to start fixing.

The assignment itself is good though, I like how it's set up. It's only very, very difficult to do so if you don't have any experience with the whole subject. My main struggle was not knowing where to start, e.g. with the form. I know it's from lack of knowledge but then, I still wouldn't know what to dig in first to keep up with it.

I finally opened this issue because I really want to get on with the Storage assignment and hope the Shelter assignment is done at least well enough to actually be able to start/finish Storage.

Sorry for the late issue/finish with Shelter, I've gotten sick in the week before and had some other issues along the way. Only curious about what I can still fix of Shelter though!

https://github.com/deannabosschert/shelter

**Comment by deannabosschert** [comment]
Just realized that it might be handy to add the readme.md aswell, oops.

How I did the assignments is in the howto.md file, although I fixed some things afterwards so it might not be as accurate as first.

**Comment by rijkvanzanten** [comment]
Hey @deannabosschert! Could you send use the link to your repo? 🙂

**Comment by deannabosschert** [comment]
Yes of course! Quite stupid and sorry for the late answer..

**Comment by wooorm** [comment]
Hey well done @deannabosschert! And congrats on the prise you won! 💪 When are you going to Istanbul?!

For startes: you handed this in after the deadline, so no points, but I’m happy to give feedback!

* Imense credits for spending so much time on it! I now it isn’t easy, I know it’s easier for others’ than for you, but you’re doing a tremendous job! 💪
* Nice use of Git (from the commit messages); you could standardise them a bit more, and they could be a bit more descriptive, but it looks great!
* For inline code in markdown, you can use one tick: `` foo `bar` `` (where `bar` is inline code), instead of three. Three ticks are used for block code https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
* Great descriptions in your how to: it looks like you really get what’s going on, and the the time to write it down, that’s awesome!
* I like req.params.johan! 👍
* There’s still something going on with your 404 not found: From your `notFound` function, and the following `get` code, it looks like `notFound` is never called for unfound animals. In `get`, you already send the correct error back (with the template error.ejs). You can use a `.use(notFound)` at the end of the stack to catch not found errors and such, but those a) relate to unmatched routes (try going to /foo/bar) or the use of `next()` in the handler for `/:id`
* tip: in your get: use `animalExists = db.has(id)` (has checks if the id exists). When it does, use `db.get(id)` to actually add the animal to `result`
* tip: use try/catch around `db.has(id)`. It throws when the id given to it is not okay, in that case you *catch* it, and respond with a 4** error! But it looks like your catch-all *notFound* also deals with that?!
* If you install `body-parser`, it gets added to `package.json`, which means that people who later do `npm install` on your code, also get `body-parser` included! They don’t need to do that themselves!
* Awesome that you added yourself as a license holder! It’s your work as well 👍
* [With your code](https://github.com/deannabosschert/shelter/blob/7e4f669accb9da4cc5e7d023a09d9365d94491fd/server/index.js#L85), your always adding an animal with id `18646`, doesn’t the database take care of the identifier automatically?
* Tip: use the same spacing everywhere: 
<img width="635" alt="screen shot 2018-03-20 at 21 57 12" src="https://user-images.githubusercontent.com/944406/37682377-b4909350-2c89-11e8-98cf-ecd2e03e91fc.png">
* tip: wrap inputs in their correspond label, e.g., `<label>Title: <input name=title></label>`, that way you don’t need `for` and `id` to link them together, and you can `label { display:block }` do you don’t need `<br>`s either! In fact, you didn’t use `id`s on inputs. One of the cool thing of labels is that you can click on them, and they’ll focus on the corresponding input, but that only works with `for`/`id`!
* `description` should probably be a textarea?
* If I go to `http://localhost:1902/form` I don’t see the form 🤔 And there’s no link to the form either?!

Anyway, great start Deanna!
