### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by theonejonahgold** [cmda-be/course-17-18#553]
I got as far as I could. I hope it suffices for the assignment, but I don't think I can handle anymore SQL. Here is my [repo](https://github.com/theonejonahgold/shelter)

**Comment by wooorm** [comment]
Heya! I’m missing docs @theonejonahgold! How do I configure your server? What env variables? How to set up the database? 🤷‍♂️

**Comment by rijkvanzanten** [comment]
@theonejonahgold 🔔

**Comment by wooorm** [comment]
@theonejonahgold Ping!

**Comment by theonejonahgold** [comment]
@wooorm @rijkvanzanten I added some documentation to the readme 👍

**Comment by rijkvanzanten** [comment]
## Feedback
* I can't submit new animals. Every time I try I get greeted by a 422 error. I've no idea what I'm doing wrong, as the page nor the terminal show any information
* Good job on the database structure! Nicely organized
* Like the added diagram
* You have added `moment` as a `devDependency`, but it's required to run in production. I installed the dependencies with `npm install --production`, which caused the server to error out on start
* You export `moment` from helpers, but include it directly from the package in the main server file. There is no reason to export moment in the helpers here.
* Slug is a really nice addition
* I noticed the existence of `delete` and `put` support, but there is no way to use them from the interface
* Your `onerror` function accepts multiple http status codes. AFAIK you can only send a single status code in HTTP, so this isn't necessary.
* The labels in the html form seem to have been corrupted a bit. It's probably [due to this line](https://github.com/cmda-be/shelter/compare/master...theonejonahgold:master#diff-b1fa52fe5e4a2d44121e42b17ada73a2R26).
* CSS / JS isn't working 😭 

All in all, very well done 😄
