### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#554]
Hi There !
Here is the [link to my repo](https://github.com/timruiterkamp/shelter)

It was a good assignment to get to know mysql and the possibilities of mysql. I had a bit of a slow start by the setup of mysql but after trying out adding databases and setting up tables the progress went quite smooth. I finally fixed the image uploading so that's one thing i'm quite happy with and that i've got to understand a bit more of setting up databases and joining their information.

Overall yet another good assignment.

**Comment by rijkvanzanten** [comment]
Heya! Well done 😄 

## Feedback
* Thanks for the install instructions!
* Nice job on the relational db schema

### SQL
* It's very common in SQL to use underscore naming for columns / tables: `shelterName` -> `shelter_name`
* IRL, you wouldn't use names as keys in relationships. The sheltername isn't guaranteed to be unique, but the primary key (ID) is.
* You use the datatype `TEXT` for all string based values. TEXT is by design _huge_ in terms of storage. You might want to consider changing most fields to a more appropriate data type. (F.e. you know `Animals.type` only accepts three values (`dog`, `rabbit`, `cat`), so that could've been an ENUM)
* All fields allow `null` as a value. As an extra form of security, you might want to disable that, so SQL will throw an error if a field is missing.

### Code
#### `package.json`
* Make sure you put packages in the right dependencies field (`body-parser` is in `devDependencies`, but should be in `dependencies`)

#### `readme.md`
* > (By choice i would recommend using [dotenv](https://www.npmjs.com/package/dotenv) for this).
  
  You already implemented `dotenv`, so you could also opt to add a `.env.example` file (with fake credentials) to make it extra easy for the user to get started :)

#### `server/index.js`
* You still import the old `db` package. Seeing you now use `mysql`, that one got deprecated
* Watch indentation and whitespace; especially in [your `animal` function](https://github.com/timruiterkamp/shelter/blob/8021612ffe81acd9334c449ddb680eaf154af0a1/server/index.js#L56-L74)
* [This code is never used](https://github.com/timruiterkamp/shelter/blob/8021612ffe81acd9334c449ddb680eaf154af0a1/server/index.js#L104-L114) because you already save the item before having it parsed through this code
* Good job on the renaming of files :)
* [You add the `.jpg` extension to all uploaded files](https://github.com/timruiterkamp/shelter/blob/8021612ffe81acd9334c449ddb680eaf154af0a1/server/index.js#L120), but there is a chance that the uploaded files is not a `image/jpeg`
* [I don't think using `db.removed()` was by design here](https://github.com/timruiterkamp/shelter/blob/8021612ffe81acd9334c449ddb680eaf154af0a1/server/index.js#L140), was it? 🙂 

### Misc
* CSS / JS isn't working 😢 
* I can enter anything into the date field.
