### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by Asprengers** [cmda-be/course-17-18#556]
Here is my [repo](https://github.com/Asprengers/shelter)
This was an assignment that I actually understood and knew what to do.

**Comment by rijkvanzanten** [comment]
Hey @Asprengers!

> This was an assignment that I actually understood and knew what to do.

Good job on the database, but I got the feeling you missed the most interesting part of the assignment 😬

**Your web app should:**
* ~Include at least eight animals in the database~ 👍 
* ~Include all animal types (dog, cat, and rabbit)~ 👍 
* Add support for getting all animals, getting one animal, removing an animal, and adding an animal
* ~Use the correct types for all fields~ 👍 
* ~Use at least two different tables~ 👍 

You were meant to update the shelter webapp to use your database instead of Titus' static `db` package 😄
