### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#559]
[repo](https://github.com/Maikxx/shelter)

I can not handle any more SQL.
After spending hours trying to get PostgreSQL working, it didn't, so I switched over to mySQL, hoping that would go better, it didn't.
For some reason this language doesn't seem to make sense to me, with examples like foo.id = ? instead of foo.id === ? or even foo.id == ?.
I am so done with it spending way over 12 hours trying to get things working. This is as far as I'll go. Everything works (when I last tested) except adding new animals, I also added a dump of four animals I added, as well as a schema.
Usually I don't get so salty, but when time pressure is on and this comes along, I don't get along well with it.

**Comment by wooorm** [comment]
@Maikxx Ping!

**Comment by Maikxx** [comment]
For what it's worth, ehm I did not indeed set a password on purpose, so that this wouldn't happen. So I just need to set a password on it?

**Comment by rijkvanzanten** [comment]
Hey @Maikxx! Your code looks pretty good, but no matter what I do, I get a 500 error.. I tried using your SQL script as found in the readme to initialize my DB. That failed due to a syntax error in the SQL:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL,
  description TEXT CHARACTER SET utf8,
  sex ENUM('male', 'female') NO' at line 6
```

I then proceeded to install the DB using the SQL file I found in your repo. It installed fine, but doesn't seem to play nicely with your code, as every page I open results in a 500 internal server error.
